# Generated by Django 5.1.3 on 2025-11-12 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_dark_mode_user_email_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changerequest',
            name='approvals',
        ),
        migrations.RemoveField(
            model_name='changerequest',
            name='submitter',
        ),
        migrations.AddField(
            model_name='changerequest',
            name='approvals_required',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='authored_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changerequest',
            name='change_type',
            field=models.CharField(choices=[('feature', 'Feature'), ('bug_fix', 'Bug Fix'), ('enhancement', 'Enhancement'), ('documentation', 'Documentation'), ('refactor', 'Refactor'), ('other', 'Other')], default='feature', max_length=20),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='target_branch',
            field=models.CharField(default='main', max_length=255),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_approvals', to=settings.AUTH_USER_MODEL)),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='api.changerequest')),
            ],
            options={
                'unique_together': {('change_request', 'approver')},
            },
        ),
    ]
