# Generated by Django 5.1.3 on 2025-11-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chatbotpersona_chatbottemplate_chatsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancecheck',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='compliancetemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
