# Generated by Django 5.1.3 on 2025-11-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_issue_issuereply_workflow_workflowexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='llm_id',
            field=models.CharField(blank=True, help_text='ID of the selected LLM model', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='temperature',
            field=models.FloatField(default=0.7, help_text='Temperature for LLM generation (0.0 to 2.0)'),
        ),
    ]
