# Generated by Django 5.1.3 on 2025-11-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_chatsession_llm_id_chatsession_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='started_by_persona',
            field=models.BooleanField(default=False, help_text='Whether this session was started by selecting a persona'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='subject',
            field=models.CharField(blank=True, help_text='Brief summary of the conversation', max_length=255, null=True),
        ),
    ]
