# Generated by Django 5.1.3 on 2025-11-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_chatsession_started_by_persona_chatsession_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotpersona',
            name='default_llm_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatbotpersona',
            name='default_max_tokens',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='chatbotpersona',
            name='default_temperature',
            field=models.FloatField(default=0.7),
        ),
    ]
