# Generated by Django 5.1.3 on 2025-11-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_projecttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='system_prompt',
            field=models.TextField(blank=True, help_text='Custom system prompt for AI assistant in this project'),
        ),
    ]
