# Generated by Django 5.1.3 on 2025-11-19 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_project_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='api.project'),
        ),
    ]
