# Generated by Django 5.1.3 on 2025-11-19 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_chatsession_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='mode',
            field=models.CharField(choices=[('ask', 'Ask'), ('plan', 'Plan'), ('agent', 'Agent'), ('persona', 'Persona')], default='ask', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectPod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod_name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error')], default='creating', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pod', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('entrypoint', models.CharField(help_text='Command to run inside the tool container', max_length=500)),
                ('runtime_image', models.CharField(blank=True, help_text='Container image to run the tool in', max_length=255)),
                ('args_schema', models.JSONField(blank=True, default=dict)),
                ('environment', models.JSONField(blank=True, default=dict)),
                ('timeout_seconds', models.IntegerField(default=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tools', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='api.project')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('project', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='enabled_tools',
            field=models.ManyToManyField(blank=True, related_name='chat_sessions', to='api.projecttool'),
        ),
        migrations.CreateModel(
            name='ToolExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('output_payload', models.JSONField(blank=True, default=dict)),
                ('logs', models.TextField(blank=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_executions', to='api.chatsession')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='api.projecttool')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('backend', 'Backend Service'), ('frontend', 'Frontend Service'), ('tooling', 'Tool Runner'), ('custom', 'Custom Service')], default='custom', max_length=20)),
                ('image', models.CharField(max_length=255)),
                ('container_name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='stopped', max_length=50)),
                ('ports', models.JSONField(blank=True, default=list)),
                ('environment', models.JSONField(blank=True, default=dict)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.projectpod')),
            ],
            options={
                'unique_together': {('pod', 'name')},
            },
        ),
    ]
