# Generated by Django 5.1.3 on 2025-12-04 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_chatsession_mode_projectpod_projecttool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creation_method',
            field=models.CharField(choices=[('blank', 'Blank Project'), ('clone', 'Clone Repository'), ('chat', 'AI-Assisted Planning'), ('template', 'Use Template')], default='blank', help_text='How this project was created', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='git_repo_url',
            field=models.CharField(blank=True, help_text='Git repository URL for cloned projects', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_using', to='api.projecttemplate'),
        ),
        migrations.AddField(
            model_name='project',
            name='workspace_image',
            field=models.CharField(choices=[('fedora:43', 'Fedora 43'), ('registry.access.redhat.com/ubi9/ubi', 'UBI 9')], default='fedora:43', help_text='Container image for AI workspace', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='workspace_mode',
            field=models.CharField(choices=[('personal', 'Personal'), ('shared', 'Shared')], default='personal', help_text='Personal or shared workspace mode', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='workspace_size',
            field=models.CharField(default='standard', help_text='Resource tier for workspace container', max_length=20),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='file_structure',
            field=models.JSONField(blank=True, default=dict, help_text='Template file structure: {files: {path: {content, executable}}, directories: []}'),
        ),
        migrations.AddField(
            model_name='projecttool',
            name='workspace_tool',
            field=models.BooleanField(default=False, help_text='Execute in workspace container via podman exec'),
        ),
        migrations.AlterField(
            model_name='projectservice',
            name='service_type',
            field=models.CharField(choices=[('backend', 'Backend Service'), ('frontend', 'Frontend Service'), ('tooling', 'Tool Runner'), ('ai-workspace', 'AI Workspace'), ('custom', 'Custom Service')], default='custom', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkspaceResourceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name (e.g., 'Light', 'Standard', 'Heavy')", max_length=100)),
                ('slug', models.SlugField(help_text='Unique identifier for API usage', max_length=100, unique=True)),
                ('cpu_limit', models.CharField(help_text="CPU limit (e.g., '1.0', '2.0', '4.0')", max_length=20)),
                ('memory_limit', models.CharField(help_text="Memory limit (e.g., '2g', '4g', '8g')", max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Set as default tier for new projects')),
                ('is_active', models.BooleanField(default=True, help_text='Available for selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tiers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workspace Resource Tier',
                'verbose_name_plural': 'Workspace Resource Tiers',
                'ordering': ['cpu_limit', 'memory_limit'],
            },
        ),
    ]
