# Generated by Django 5.1.3 on 2025-12-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_project_creation_method_project_git_repo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectservice',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Service-specific configuration like image_digest, resource_limits, etc.'),
        ),
    ]
