# Generated by Django 5.1.3 on 2025-12-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_projectservice_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='branch',
            field=models.CharField(blank=True, default='main', help_text='Git branch name for cloned projects', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='provisioning_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of workspace provisioning', max_length=20),
        ),
    ]
