# Generated by Django 5.1.3 on 2026-01-03 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_project_branch_project_provisioning_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='log_retention_days',
            field=models.IntegerField(default=30, help_text='Number of days to retain provisioning logs (0 = keep forever)'),
        ),
        migrations.CreateModel(
            name='ProvisioningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('step_name', models.CharField(blank=True, help_text="Step identifier (e.g., 'clone_repo', 'provision_services')", max_length=100)),
                ('message', models.TextField(help_text='Human-readable log message')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured data (service names, errors, etc.)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_logs', to='api.project')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['project', 'timestamp'], name='api_provisi_project_5c9bbc_idx'), models.Index(fields=['project', 'level'], name='api_provisi_project_a4f2ff_idx')],
            },
        ),
    ]
