# Generated by Django 5.1.3 on 2026-01-07 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_projectservice_autostart_cpu_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='completion_tokens',
            field=models.IntegerField(blank=True, help_text='Number of tokens in the completion', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Estimated cost in USD for this message', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='prompt_tokens',
            field=models.IntegerField(blank=True, help_text='Number of tokens in the prompt', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='total_tokens',
            field=models.IntegerField(blank=True, help_text='Total tokens used (prompt + completion)', null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='selected_model',
            field=models.CharField(blank=True, help_text="Model ID from the provider (e.g., 'openai/gpt-4', 'anthropic/claude-3-opus')", max_length=200),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='llm_id',
            field=models.CharField(blank=True, help_text='DEPRECATED: Legacy LLM ID, migrating to provider system', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('system', 'System-wide'), ('team', 'Team-level'), ('project', 'Project-level'), ('user', 'User-level')], help_text='Configuration level: system, team, project, or user', max_length=20)),
                ('provider_type', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('openrouter', 'OpenRouter'), ('ollama', 'Ollama'), ('vllm', 'vLLM'), ('litemaas', 'LiteMaaS'), ('custom', 'Custom Provider')], help_text='Type of LLM provider', max_length=50)),
                ('instance_name', models.CharField(help_text="User-friendly name for this provider instance (e.g., 'My OpenRouter', 'Team vLLM')", max_length=200)),
                ('api_key', models.TextField(blank=True, help_text='Encrypted API key for the provider (encrypted via Fernet)')),
                ('base_url', models.URLField(blank=True, help_text='Custom base URL for API endpoint (for vLLM, custom providers)', max_length=500, null=True)),
                ('available_models', models.JSONField(blank=True, default=list, help_text='Cached list of available models with pricing: [{id, name, pricing: {prompt, completion}, context_length}]')),
                ('pricing_data', models.JSONField(blank=True, default=dict, help_text='Additional provider-level pricing configuration')),
                ('last_discovery', models.DateTimeField(blank=True, help_text='Last time models were discovered from provider API', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this provider is available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Admin who created this provider', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_llm_providers', to=settings.AUTH_USER_MODEL)),
                ('scope_project', models.ForeignKey(blank=True, help_text='Project for project-scoped providers', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_providers', to='api.project')),
                ('scope_team', models.ForeignKey(blank=True, help_text='Team for team-scoped providers', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_providers', to='api.team')),
                ('scope_user', models.ForeignKey(blank=True, help_text='User for user-scoped providers', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scope', 'instance_name'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='used_by_provider',
            field=models.ForeignKey(blank=True, help_text='Provider used for this message (for cost allocation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='api.llmprovider'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Selected LLM provider for this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='api.llmprovider'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['used_by_provider', 'created_at'], name='api_chatmes_used_by_1579f0_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='api_chatmes_session_2462c9_idx'),
        ),
        migrations.AddIndex(
            model_name='llmprovider',
            index=models.Index(fields=['scope', 'is_active'], name='api_llmprov_scope_4c7ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='llmprovider',
            index=models.Index(fields=['scope_team', 'is_active'], name='api_llmprov_scope_t_3f5a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='llmprovider',
            index=models.Index(fields=['scope_project', 'is_active'], name='api_llmprov_scope_p_0ee522_idx'),
        ),
        migrations.AddIndex(
            model_name='llmprovider',
            index=models.Index(fields=['scope_user', 'is_active'], name='api_llmprov_scope_u_6eb2ee_idx'),
        ),
    ]
