# Generated by Django 5.1.3 on 2026-01-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_chatmessage_completion_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_llm_model',
            field=models.CharField(blank=True, help_text='Default LLM model for this user (e.g., openai/gpt-4, anthropic/claude-3)', max_length=500, null=True),
        ),
    ]
