# Generated by Django 5.1.3 on 2026-01-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_default_llm_model_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='reasoning',
            field=models.TextField(blank=True, help_text="Agent's reasoning/thinking process", null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='tool_calls',
            field=models.JSONField(blank=True, default=list, help_text='List of tool calls made by agent'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='agent_iterations',
            field=models.IntegerField(default=0, help_text='Number of agent loop iterations in this session'),
        ),
        migrations.AddField(
            model_name='project',
            name='agent_framework',
            field=models.CharField(choices=[('langgraph', 'LangGraph')], default='langgraph', help_text='Agent framework for AI chat in this project', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='allowed_commands',
            field=models.JSONField(default=list, help_text='List of allowed shell commands for workspace tools'),
        ),
        migrations.AddField(
            model_name='project',
            name='command_timeout',
            field=models.IntegerField(default=60, help_text='Timeout in seconds for tool command execution'),
        ),
    ]
