# Generated by Django 5.1.3 on 2026-01-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_add_agent_framework_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='supports_function_calling',
            field=models.BooleanField(default=False, help_text='Whether this provider supports native function/tool calling'),
        ),
    ]
