# Generated by Django 5.1.3 on 2026-02-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_llmprovider_supports_function_calling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='mode',
            field=models.CharField(choices=[('ask', 'Ask'), ('plan', 'Plan'), ('agent', 'Agent'), ('persona', 'Persona'), ('deep', 'Deep')], default='ask', max_length=20),
        ),
    ]
