# Generated by Django 5.1.3 on 2026-04-24 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_organization_hierarchy_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationGitConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider_type', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket'), ('gitea', 'Gitea'), ('generic-git', 'Generic Git')], max_length=20)),
                ('auth_type', models.CharField(choices=[('pat', 'Personal Access Token'), ('oauth', 'OAuth'), ('app', 'App Installation'), ('ssh', 'SSH')], default='pat', max_length=20)),
                ('base_url', models.URLField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True)),
                ('credential', models.TextField(blank=True, help_text='Encrypted Git credential (token, app secret, or SSH key)')),
                ('repository_cache', models.JSONField(blank=True, default=list, help_text='Cached repository identifiers available through this connection')),
                ('webhook_enabled', models.BooleanField(default=False)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(choices=[('unknown', 'Unknown'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organization_git_connections', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_connections', to='api.organization')),
            ],
            options={
                'ordering': ['organization__name', 'name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='organizationgitconnection',
            index=models.Index(fields=['organization', 'provider_type'], name='api_orggitc_organiz_b01277_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationgitconnection',
            index=models.Index(fields=['organization', 'last_test_status'], name='api_orggitc_organiz_d0d236_idx'),
        ),
    ]