# Generated by Django 5.1.3 on 2026-04-24 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_personalgitconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSourceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_scope', models.CharField(blank=True, choices=[('organization', 'Shared organization connection'), ('personal', 'Personal connection')], max_length=20)),
                ('source_provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket'), ('gitea', 'Gitea'), ('generic-git', 'Generic Git'), ('raw-compose', 'Raw Compose / Dockerfile'), ('docker-registry', 'Docker Registry / Hub')], default='github', max_length=20)),
                ('source_ref', models.CharField(blank=True, default='main', max_length=255)),
                ('watch_paths', models.JSONField(blank=True, default=list)),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual'), ('push', 'On Push'), ('schedule', 'Schedule')], default='manual', max_length=20)),
                ('auto_deploy_enabled', models.BooleanField(default=False)),
                ('submodules_enabled', models.BooleanField(default=False)),
                ('schedule', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source_settings', to='api.app')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_source_settings', to=settings.AUTH_USER_MODEL)),
                ('organization_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_sources', to='api.organizationgitconnection')),
                ('personal_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_sources', to='api.personalgitconnection')),
            ],
            options={
                'ordering': ['app__environment__name', 'app__name'],
            },
        ),
    ]