# Generated by Django 5.1.3 on 2026-04-24 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_appsourcesettings_source_contract'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organizationgitconnection',
            new_name='api_organiz_organiz_197de9_idx',
            old_name='api_orggitc_organiz_b01277_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationgitconnection',
            new_name='api_organiz_organiz_5b9209_idx',
            old_name='api_orggitc_organiz_d0d236_idx',
        ),
        migrations.RenameIndex(
            model_name='personalgitconnection',
            new_name='api_persona_user_id_ae2320_idx',
            old_name='api_persgit_user_id_7e5a95_idx',
        ),
        migrations.RenameIndex(
            model_name='personalgitconnection',
            new_name='api_persona_user_id_61e1b4_idx',
            old_name='api_persgit_user_id_57a12a_idx',
        ),
    ]
