"""SSH MVP: sync a compose project to a remote host and `docker compose up -d`.

Uses OpenSSH via subprocess (no paramiko dependency). Writes a temp private
key with mode 0600, generates Traefik file-provider YAML from a routes list,
then rsync/scp + remote compose up.

Pragmatic sketch for Issue 15 P3/P4 — not a full job runner.
"""

from __future__ import annotations

import logging
import os
import shlex
import subprocess
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Sequence

logger = logging.getLogger(__name__)

# Prefer system-wide Traefik watch dir; also write project-local copy.
REMOTE_DYNAMIC_DIR = "/etc/everflow/dynamic"
PROJECT_TRAEFIK_REL = ".everflow/traefik-routes.yml"


@dataclass
class DeployRoute:
    """One Host(domain) → service:port mapping for Traefik."""

    name: str
    domain: str
    service: str
    port: int
    entrypoint: str = "web"
    url: str | None = None  # override loadBalancer URL if set

    @classmethod
    def from_mapping(cls, data: dict[str, Any]) -> DeployRoute:
        name = str(data.get("name") or data.get("service") or "app")
        domain = str(data.get("domain") or data.get("host") or "")
        service = str(data.get("service") or name)
        port = int(data.get("port") or 80)
        entrypoint = str(data.get("entrypoint") or "web")
        url = data.get("url")
        if not domain:
            raise ValueError("route.domain (or host) is required")
        return cls(
            name=name.replace(" ", "-").lower(),
            domain=domain,
            service=service.replace(" ", "-").lower(),
            port=port,
            entrypoint=entrypoint,
            url=str(url) if url else None,
        )


@dataclass
class DeployRemoteResult:
    ok: bool
    remote_dir: str
    compose_path: str
    routes_path: str
    log_lines: list[str] = field(default_factory=list)
    error: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "ok": self.ok,
            "remote_dir": self.remote_dir,
            "compose_path": self.compose_path,
            "routes_path": self.routes_path,
            "log_lines": self.log_lines,
            "error": self.error,
        }


def render_traefik_routes_yml(routes: Sequence[DeployRoute]) -> str:
    """Render Traefik v3 file-provider YAML: Host(`domain`) → http://service:port."""
    if not routes:
        return "# no routes\nhttp:\n  routers: {}\n  services: {}\n"

    lines = [
        "# Generated by everflow deploy_remote — do not edit by hand",
        "http:",
        "  routers:",
    ]
    for r in routes:
        lines.extend(
            [
                f"    {r.name}:",
                f'      rule: "Host(`{r.domain}`)"',
                "      entryPoints:",
                f"        - {r.entrypoint}",
                f"      service: {r.service}",
            ]
        )
    lines.append("  services:")
    for r in routes:
        target = r.url or f"http://{r.service}:{r.port}"
        lines.extend(
            [
                f"    {r.service}:",
                "      loadBalancer:",
                "        servers:",
                f'          - url: "{target}"',
            ]
        )
    lines.append("")
    return "\n".join(lines)


def _write_temp_key(private_key_pem: str) -> Path:
    text = private_key_pem.strip() + "\n"
    fd, path_str = tempfile.mkstemp(prefix="everflow-deploy-", suffix=".pem")
    path = Path(path_str)
    try:
        os.write(fd, text.encode("utf-8"))
    finally:
        os.close(fd)
    os.chmod(path, 0o600)
    return path


def _ssh_base(host: str, user: str, port: int, key_path: Path) -> list[str]:
    return [
        "ssh",
        "-i",
        str(key_path),
        "-p",
        str(port),
        "-o",
        "StrictHostKeyChecking=accept-new",
        "-o",
        "BatchMode=yes",
        "-o",
        "IdentitiesOnly=yes",
        f"{user}@{host}",
    ]


def _run(
    cmd: list[str],
    *,
    log_lines: list[str],
    timeout: int = 300,
    check: bool = True,
) -> subprocess.CompletedProcess[str]:
    log_lines.append("$ " + " ".join(shlex.quote(c) for c in cmd))
    logger.info("deploy_remote: %s", " ".join(cmd[:6]) + ("…" if len(cmd) > 6 else ""))
    try:
        proc = subprocess.run(
            cmd,
            check=False,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
    except subprocess.TimeoutExpired as exc:
        log_lines.append(f"TIMEOUT after {timeout}s")
        raise RuntimeError(f"command timed out after {timeout}s: {cmd[0]}") from exc
    if proc.stdout:
        log_lines.extend(proc.stdout.rstrip().splitlines())
    if proc.stderr:
        log_lines.extend(proc.stderr.rstrip().splitlines())
    if check and proc.returncode != 0:
        raise RuntimeError(
            f"command failed ({proc.returncode}): {' '.join(cmd[:4])}…\n"
            f"{(proc.stderr or proc.stdout or '').strip()}"
        )
    return proc


def _has_rsync() -> bool:
    from shutil import which

    return which("rsync") is not None


def execute_compose_up(
    host: str,
    user: str,
    port: int,
    private_key: str,
    local_workspace_hint: str | None,
    compose_rel_path: str,
    routes: Sequence[DeployRoute | dict[str, Any]],
    *,
    remote_dir: str = "/opt/everflow/apps/project",
    dry_run: bool = False,
) -> DeployRemoteResult:
    """SSH mkdir + sync workspace + write Traefik routes + docker compose up -d.

    Args:
        host: SSH hostname or IP
        user: SSH user (e.g. everflow)
        port: SSH port
        private_key: PEM / OpenSSH private key material
        local_workspace_hint: Local directory to rsync/scp (optional; if missing,
            only remote mkdir + routes + compose up of existing remote_dir)
        compose_rel_path: Compose file path relative to remote_dir
        routes: Host→service:port list
        remote_dir: Absolute path on the remote host
        dry_run: If True, skip network commands and only render artifacts locally
    """
    log_lines: list[str] = []
    parsed: list[DeployRoute] = [
        r if isinstance(r, DeployRoute) else DeployRoute.from_mapping(r) for r in routes
    ]
    yml = render_traefik_routes_yml(parsed)
    compose_rel = compose_rel_path.strip().lstrip("./") or "docker-compose.yml"
    routes_remote = f"{remote_dir.rstrip('/')}/{PROJECT_TRAEFIK_REL}"
    system_routes = f"{REMOTE_DYNAMIC_DIR.rstrip('/')}/routes.yml"

    if dry_run:
        log_lines.append(f"[dry-run] would sync → {user}@{host}:{remote_dir}")
        log_lines.append(f"[dry-run] routes ({len(parsed)}):\n{yml}")
        return DeployRemoteResult(
            ok=True,
            remote_dir=remote_dir,
            compose_path=compose_rel,
            routes_path=routes_remote,
            log_lines=log_lines,
        )

    key_path = _write_temp_key(private_key)
    try:
        ssh = _ssh_base(host, user, port, key_path)
        # mkdir remote project + .everflow; best-effort system dynamic dir
        everflow_subdir = str(Path(remote_dir) / Path(PROJECT_TRAEFIK_REL).parent)
        mkdir_cmd = (
            f"mkdir -p {shlex.quote(everflow_subdir)} "
            f"&& (sudo mkdir -p {shlex.quote(REMOTE_DYNAMIC_DIR)} 2>/dev/null || "
            f"mkdir -p {shlex.quote(REMOTE_DYNAMIC_DIR)} 2>/dev/null || true)"
        )
        _run([*ssh, mkdir_cmd], log_lines=log_lines)

        # Sync local workspace if provided
        local = (local_workspace_hint or "").strip()
        if local and Path(local).is_dir():
            if _has_rsync():
                rsync = [
                    "rsync",
                    "-az",
                    "--delete",
                    "-e",
                    f"ssh -i {shlex.quote(str(key_path))} -p {port} "
                    f"-o StrictHostKeyChecking=accept-new -o BatchMode=yes -o IdentitiesOnly=yes",
                    f"{local.rstrip('/')}/",
                    f"{user}@{host}:{remote_dir.rstrip('/')}/",
                ]
                _run(rsync, log_lines=log_lines, timeout=600)
            else:
                # Fallback: tar over ssh (sketch)
                log_lines.append("rsync not found; using tar|ssh fallback")
                tar = subprocess.Popen(
                    ["tar", "-C", local, "-czf", "-", "."],
                    stdout=subprocess.PIPE,
                )
                try:
                    proc = subprocess.run(
                        [*ssh, f"tar -C {shlex.quote(remote_dir)} -xzf -"],
                        stdin=tar.stdout,
                        capture_output=True,
                        text=True,
                        timeout=600,
                        check=False,
                    )
                    if tar.stdout:
                        tar.stdout.close()
                    tar.wait(timeout=30)
                finally:
                    if tar.poll() is None:
                        tar.kill()
                if proc.stdout:
                    log_lines.extend(proc.stdout.rstrip().splitlines())
                if proc.stderr:
                    log_lines.extend(proc.stderr.rstrip().splitlines())
                if proc.returncode != 0:
                    raise RuntimeError("tar|ssh sync failed")
                log_lines.append("$ tar|ssh sync OK")
        else:
            log_lines.append(
                "no local_workspace_hint (or not a dir) — "
                "assuming compose project already on remote (git pull stub skipped)"
            )
            # Optional stub: git pull if .git exists
            _run(
                [
                    *ssh,
                    f"if [ -d {shlex.quote(remote_dir)}/.git ]; then "
                    f"git -C {shlex.quote(remote_dir)} pull --ff-only; "
                    f"else echo 'no .git — skip pull'; fi",
                ],
                log_lines=log_lines,
                check=False,
            )

        # Write Traefik routes via ssh heredoc-ish (base64 to avoid quoting hell)
        import base64

        b64 = base64.b64encode(yml.encode("utf-8")).decode("ascii")
        write_routes = (
            f"echo {shlex.quote(b64)} | base64 -d > {shlex.quote(routes_remote)} && "
            f"(sudo cp {shlex.quote(routes_remote)} {shlex.quote(system_routes)} 2>/dev/null || "
            f"cp {shlex.quote(routes_remote)} {shlex.quote(system_routes)} 2>/dev/null || "
            f"echo 'note: could not copy to {system_routes} — project copy at {routes_remote}')"
        )
        _run([*ssh, write_routes], log_lines=log_lines)

        compose_file = f"{remote_dir.rstrip('/')}/{compose_rel}"
        up_cmd = (
            f"cd {shlex.quote(remote_dir)} && "
            f"(docker compose -f {shlex.quote(compose_file)} up -d || "
            f"docker-compose -f {shlex.quote(compose_file)} up -d)"
        )
        _run([*ssh, up_cmd], log_lines=log_lines, timeout=600)

        log_lines.append("deploy_remote: compose up completed")
        return DeployRemoteResult(
            ok=True,
            remote_dir=remote_dir,
            compose_path=compose_rel,
            routes_path=routes_remote,
            log_lines=log_lines,
        )
    except Exception as exc:  # noqa: BLE001 — surface to API
        logger.exception("deploy_remote failed for %s@%s", user, host)
        log_lines.append(f"ERROR: {exc}")
        return DeployRemoteResult(
            ok=False,
            remote_dir=remote_dir,
            compose_path=compose_rel,
            routes_path=routes_remote,
            log_lines=log_lines,
            error=str(exc),
        )
    finally:
        try:
            key_path.unlink(missing_ok=True)
        except OSError:
            logger.warning("failed to unlink temp key %s", key_path)
