#!/usr/bin/env bash
# Everflow embedded OCI registry helpers.
#
# The stack always runs a private Distribution registry (compose service
# `registry`). Host pushes use localhost:PORT; containers/msb use registry:PORT.
# Same repository paths — one push is enough.
#
# Usage (from repo root):
#   ./deploy/local-registry.sh up
#   ./deploy/local-registry.sh seed              # online: mirror upstream + build/push all
#   ./deploy/local-registry.sh mirror-upstream
#   ./deploy/local-registry.sh build-push        # build Everflow images → local registry
#   ./deploy/local-registry.sh mirror-ghcr       # retag published GHCR → local (no build)
#   ./deploy/local-registry.sh status
#   ./deploy/local-registry.sh export /path/everflow-images.tar
#   ./deploy/local-registry.sh import /path/everflow-images.tar
#   ./deploy/local-registry.sh env-snippet
#
# Env:
#   REGISTRY_HOST_PORT=5000
#   EVERFLOW_IMAGE_TAG=latest
#   CONTAINER_ENGINE=docker|podman
#   ONLY=guest,backend   (build-push subset)
#   SKIP_BUILD_GUEST=true
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT}"

PORT="${REGISTRY_HOST_PORT:-5000}"
TAG="${EVERFLOW_IMAGE_TAG:-latest}"
# Host-facing registry (compose publish + docker push)
HOST_REG="${LOCAL_REGISTRY_HOST:-localhost:${PORT}}"
# Compose DNS name used by sandbox-agent / msb
INT_REG="${INTERNAL_REGISTRY_HOST:-registry:${PORT}}"
# Repository namespace inside the registry
NS="${LOCAL_REGISTRY_NS:-everflow}"
COMPOSE_FILE="${COMPOSE_FILE:-docker-compose.yml}"
PUBLIC_GHCR="${EVERFLOW_PUBLIC_REGISTRY:-ghcr.io/real-limitless}"
ENGINE="${CONTAINER_ENGINE:-}"

# Upstream sources → local names under NS/
UPSTREAM_MICRO_SRC="${UPSTREAM_MICRO_SRC:-ghcr.io/superradcompany/microsandbox:latest}"
UPSTREAM_SEARXNG_SRC="${UPSTREAM_SEARXNG_SRC:-docker.io/searxng/searxng:latest}"
UPSTREAM_REGISTRY_SRC="${UPSTREAM_REGISTRY_SRC:-docker.io/library/registry:2}"

log() { echo "  ▸ $*"; }
ok() { echo "    ✓ $*"; }
warn() { echo "    ! $*" >&2; }
die() { echo "  ✗ $*" >&2; exit 1; }

detect_engine() {
  if [[ -n "${ENGINE}" ]]; then
    echo "${ENGINE}"
    return
  fi
  if command -v docker >/dev/null 2>&1; then
    echo docker
  elif command -v podman >/dev/null 2>&1; then
    echo podman
  else
    die "need docker or podman"
  fi
}

# True when the selected ENGINE is Podman (including docker→podman shim).
# Never treat "podman is installed alongside docker" as Podman mode — that mixed
# the Docker image store (pull) with the Podman store (tag/push) → image not known.
is_podman_cli() {
  case "${ENGINE}" in
    podman) return 0 ;;
  esac
  # docker binary is actually podman (podman-docker package)
  if command -v podman >/dev/null 2>&1 && [[ "$(command -v docker 2>/dev/null || true)" == "$(command -v podman 2>/dev/null || true)" ]]; then
    return 0
  fi
  # Only sniff the engine binary itself — do not grep `docker info` (false positives)
  if [[ "${ENGINE}" == "docker" ]] && "${ENGINE}" version 2>&1 | head -n 5 | grep -qiE 'podman|Emulate Docker CLI using podman'; then
    return 0
  fi
  return 1
}

ENGINE="$(detect_engine)"
# Prefer explicit CONTAINER_ENGINE when caller (scripts/everflow) sets it
if [[ -n "${CONTAINER_ENGINE:-}" ]]; then
  ENGINE="${CONTAINER_ENGINE}"
fi
export ENGINE CONTAINER_ENGINE="${ENGINE}"

compose() {
  if "${ENGINE}" compose version >/dev/null 2>&1; then
    "${ENGINE}" compose "$@"
    return
  fi
  if [[ "${ENGINE}" == "podman" ]] && command -v podman-compose >/dev/null 2>&1; then
    podman-compose "$@"
    return
  fi
  if command -v docker-compose >/dev/null 2>&1; then
    docker-compose "$@"
    return
  fi
  die "${ENGINE} compose plugin not found"
}

# Allow HTTP push/pull to the embedded registry (localhost is plain HTTP).
# Podman: drop-in registries.conf + --tls-verify=false on push.
# Docker: requires daemon insecure-registries (we only warn if missing).
# Always pull/tag/push with the same ${ENGINE} binary (one image store).
ensure_insecure_local_registry() {
  local host_only="${HOST_REG%%/*}" # localhost:5000
  local loc_host="${host_only%:*}"
  local loc_port="${host_only##*:}"
  [[ "${loc_port}" == "${loc_host}" ]] && loc_port="${PORT}"

  if [[ "${ENGINE}" == "podman" ]] || is_podman_cli; then
    local conf_dir conf
    conf_dir="${HOME}/.config/containers/registries.conf.d"
    conf="${conf_dir}/everflow-local-registry.conf"
    mkdir -p "${conf_dir}"
    cat >"${conf}" <<EOF
# Generated by Everflow — allow HTTP local registry (do not edit by hand; re-run seed to refresh)
[[registry]]
location = "localhost:${loc_port}"
insecure = true

[[registry]]
location = "127.0.0.1:${loc_port}"
insecure = true

[[registry]]
location = "registry:${loc_port}"
insecure = true
EOF
    ok "Podman insecure registry config → ${conf}"
    return 0
  fi

  # Real Docker: check daemon for insecure-registries
  if "${ENGINE}" info 2>/dev/null | grep -qiE "Insecure Registries:.*localhost:${loc_port}|Insecure Registries:.*127.0.0.1:${loc_port}"; then
    ok "Docker already allows insecure ${host_only}"
    return 0
  fi
  # Best-effort parse of docker info Registry Config / default loopback CIDRs
  if "${ENGINE}" info --format '{{json .RegistryConfig.InsecureRegistryCIDRs}}' 2>/dev/null | grep -qE "localhost|127.0.0.0"; then
    ok "Docker insecure registry CIDR may cover localhost"
    return 0
  fi
  if "${ENGINE}" info 2>/dev/null | grep -A20 -i 'Insecure Registries' | grep -qE '127\.0\.0\.0/8|::1/128'; then
    ok "Docker loopback insecure CIDR covers ${host_only}"
    return 0
  fi
  warn "Docker may reject HTTP pushes to ${host_only}."
  warn "Add to /etc/docker/daemon.json then restart Docker:"
  warn "  {\"insecure-registries\": [\"localhost:${loc_port}\", \"127.0.0.1:${loc_port}\"]}"
  return 0
}

engine_push() {
  local ref="$1"
  if [[ "${ENGINE}" == "podman" ]]; then
    podman push --tls-verify=false "${ref}"
    return
  fi
  "${ENGINE}" push "${ref}"
}

engine_pull() {
  local ref="$1"
  if [[ "${ENGINE}" == "podman" ]]; then
    if [[ "${ref}" == localhost:* || "${ref}" == 127.0.0.1:* || "${ref}" == registry:* ]]; then
      podman pull --tls-verify=false "${ref}"
    else
      podman pull "${ref}"
    fi
    return
  fi
  "${ENGINE}" pull "${ref}"
}

engine_tag() {
  local src="$1" dest="$2"
  "${ENGINE}" tag "${src}" "${dest}"
}

engine_image_exists() {
  local ref="$1"
  if [[ "${ENGINE}" == "podman" ]]; then
    podman image exists "${ref}" 2>/dev/null
    return
  fi
  "${ENGINE}" image inspect "${ref}" >/dev/null 2>&1
}

host_ref() {
  # name without namespace, e.g. everflow-backend → localhost:5000/everflow/everflow-backend:tag
  local name="$1"
  local t="${2:-${TAG}}"
  echo "${HOST_REG}/${NS}/${name}:${t}"
}

int_ref() {
  local name="$1"
  local t="${2:-${TAG}}"
  echo "${INT_REG}/${NS}/${name}:${t}"
}

registry_v2_ok() {
  if command -v curl >/dev/null 2>&1; then
    curl -sf "http://127.0.0.1:${PORT}/v2/" >/dev/null 2>&1
    return
  fi
  if command -v wget >/dev/null 2>&1; then
    wget -q -O /dev/null "http://127.0.0.1:${PORT}/v2/" 2>/dev/null
    return
  fi
  # Fallback via engine
  "${ENGINE}" run --rm --network host curlimages/curl:8.5.0 -sf "http://127.0.0.1:${PORT}/v2/" >/dev/null 2>&1
}

wait_registry() {
  local i
  for i in $(seq 1 40); do
    if registry_v2_ok; then
      return 0
    fi
    sleep 0.5
  done
  return 1
}

cmd_up() {
  log "container engine: ${ENGINE}"
  ensure_insecure_local_registry
  log "Starting registry service (${COMPOSE_FILE})"
  compose -f "${COMPOSE_FILE}" up -d registry
  if wait_registry; then
    ok "registry healthy at http://127.0.0.1:${PORT}/v2/"
  else
    die "registry did not become ready on port ${PORT}"
  fi
}

push_image() {
  local src="$1"
  local dest="$2"
  log "Push ${dest} (engine=${ENGINE})"
  if ! engine_image_exists "${src}"; then
    warn "image not in ${ENGINE} store: ${src}"
    warn "pull and push must use the same engine (set CONTAINER_ENGINE=docker or podman)."
    return 1
  fi
  engine_tag "${src}" "${dest}"
  if ! engine_push "${dest}"; then
    warn "push failed for ${dest}"
    warn "HTTP registries need insecure access (Podman) or insecure-registries (Docker)."
    warn "  Podman: auto-written ~/.config/containers/registries.conf.d/everflow-local-registry.conf"
    warn "          and push uses --tls-verify=false"
    warn "  Docker:  daemon.json → \"insecure-registries\": [\"localhost:${PORT}\"] then restart docker"
    return 1
  fi
  ok "pushed ${dest}"
}

mirror_one() {
  local src="$1"
  local local_name="$2"
  local dest
  dest="$(host_ref "${local_name}")"
  log "Mirror ${src} → ${dest}"
  if ! engine_pull "${src}"; then
    warn "pull failed: ${src}"
    return 1
  fi
  if ! engine_image_exists "${src}"; then
    warn "after pull, ${src} missing from ${ENGINE} store — check CONTAINER_ENGINE / docker vs podman"
    return 1
  fi
  push_image "${src}" "${dest}"
}

cmd_mirror_upstream() {
  cmd_up
  mirror_one "${UPSTREAM_MICRO_SRC}" "upstream-microsandbox"
  mirror_one "${UPSTREAM_SEARXNG_SRC}" "upstream-searxng"
  # Keep registry:2 on the host engine only (bootstrap). Also tag for export bundles.
  log "Ensure host has registry bootstrap image ${UPSTREAM_REGISTRY_SRC}"
  engine_pull "${UPSTREAM_REGISTRY_SRC}" || warn "could not pull ${UPSTREAM_REGISTRY_SRC}"
  # Optional mirror for airgap export completeness (not used as compose self-image)
  push_image "${UPSTREAM_REGISTRY_SRC}" "$(host_ref upstream-registry 2)" || true
  ok "upstream mirrors complete"
}

cmd_build_push() {
  cmd_up
  local only="${ONLY:-}"
  log "Building Everflow images → ${HOST_REG}/${NS} tag=${TAG}"
  EVERFLOW_REGISTRY="${HOST_REG}/${NS}" \
    EVERFLOW_IMAGE_TAG="${TAG}" \
    PUSH=true \
    ONLY="${only}" \
    CONTAINER_ENGINE="${ENGINE}" \
    EVERFLOW_PUSH_TLS_VERIFY=false \
    MICRO_SANDBOX_BASE="${MICRO_SANDBOX_BASE:-$(host_ref upstream-microsandbox)}" \
    "${ROOT}/deploy/build-images.sh"
  ok "build-push complete"
  echo ""
  echo "  Guest ref for sandbox-agent (msb):"
  echo "    $(int_ref everflow-sandbox-guest)"
  echo "  Compose image refs (host pull):"
  echo "    $(host_ref everflow-backend)"
}

cmd_mirror_ghcr() {
  cmd_up
  local name src
  log "Mirroring published images from ${PUBLIC_GHCR} tag=${TAG}"
  echo "  Required:"
  for name in everflow-frontend everflow-backend everflow-sandbox-agent everflow-sandbox-guest; do
    echo "    ${PUBLIC_GHCR}/${name}:${TAG}"
  done
  for name in everflow-frontend everflow-backend everflow-sandbox-agent everflow-sandbox-guest; do
    src="${PUBLIC_GHCR}/${name}:${TAG}"
    if ! mirror_one "${src}" "${name}"; then
      die "GHCR pull/mirror failed for ${src}

  INSTALL_MODE=ghcr requires these published packages (see docs/images.md):
    ${PUBLIC_GHCR}/everflow-frontend:${TAG}
    ${PUBLIC_GHCR}/everflow-backend:${TAG}
    ${PUBLIC_GHCR}/everflow-sandbox-agent:${TAG}
    ${PUBLIC_GHCR}/everflow-sandbox-guest:${TAG}

  CI workflow: .github/workflows/publish-images.yml
  Until a maintainer publishes them, use BUILD_FROM_SOURCE=1 / INSTALL_MODE=build.
  This command does not fall back to a local compile."
    fi
  done
  ok "GHCR → local mirror complete"
}

cmd_seed() {
  log "Seeding local registry (online machine)"
  cmd_mirror_upstream
  if [[ "${SEED_FROM_GHCR:-0}" == "1" || "${SEED_FROM_GHCR:-}" == "true" ]]; then
    cmd_mirror_ghcr
  else
    cmd_build_push
  fi
  cmd_write_env_hints
  ok "seed complete — start stack with: ./scripts/everflow install"
}

cmd_status() {
  if ! registry_v2_ok; then
    warn "registry not reachable at http://127.0.0.1:${PORT}/v2/"
    warn "Run: ./deploy/local-registry.sh up"
    return 1
  fi
  ok "registry up on :${PORT}"
  local catalog
  if command -v curl >/dev/null 2>&1; then
    catalog="$(curl -sf "http://127.0.0.1:${PORT}/v2/_catalog" 2>/dev/null || true)"
  else
    catalog="$("${ENGINE}" run --rm --network host curlimages/curl:8.5.0 -sf "http://127.0.0.1:${PORT}/v2/_catalog" 2>/dev/null || true)"
  fi
  echo "  catalog: ${catalog:-"(empty or unreadable)"}"
  echo ""
  echo "  Expected repos under ${NS}/:"
  local r
  for r in \
    everflow-frontend everflow-backend everflow-sandbox-agent everflow-sandbox-guest \
    upstream-microsandbox upstream-searxng; do
    # Catalog JSON: {"repositories":["everflow/everflow-backend",...]}
    if echo "${catalog}" | grep -qE "\"${NS}/${r}\"|\"${r}\""; then
      ok "${NS}/${r}"
    else
      warn "missing ${NS}/${r}"
    fi
  done
}

# Images included in airgap tarball (host-local tags after pull from registry or seed)
export_list() {
  cat <<EOF
$(host_ref everflow-frontend)
$(host_ref everflow-backend)
$(host_ref everflow-sandbox-agent)
$(host_ref everflow-sandbox-guest)
$(host_ref upstream-microsandbox)
$(host_ref upstream-searxng)
$(host_ref upstream-registry 2)
${UPSTREAM_REGISTRY_SRC}
EOF
}

cmd_export() {
  local out="${1:-}"
  [[ -n "${out}" ]] || die "usage: $0 export /path/everflow-images.tar"
  cmd_up
  log "Pulling local registry images to host store for export"
  local img
  local -a imgs=()
  while IFS= read -r img; do
    [[ -z "${img}" ]] && continue
    if "${ENGINE}" pull "${img}" 2>/dev/null || "${ENGINE}" image inspect "${img}" >/dev/null 2>&1; then
      imgs+=("${img}")
    else
      warn "skip missing ${img}"
    fi
  done < <(export_list)

  [[ ${#imgs[@]} -gt 0 ]] || die "no images to export — run seed first"
  log "Saving ${#imgs[@]} images → ${out}"
  "${ENGINE}" save -o "${out}" "${imgs[@]}"
  ok "wrote ${out}"
  echo "  Transfer to offline host, then: ./deploy/local-registry.sh import ${out}"
}

cmd_import() {
  local archive="${1:-}"
  [[ -n "${archive}" && -f "${archive}" ]] || die "usage: $0 import /path/everflow-images.tar"
  log "Loading ${archive}"
  "${ENGINE}" load -i "${archive}"
  cmd_up
  log "Pushing loaded images into local registry"
  local img name t
  # Push any everflow/* tags that match our host registry prefix
  while IFS= read -r img; do
    [[ -z "${img}" ]] && continue
    if "${ENGINE}" image inspect "${img}" >/dev/null 2>&1; then
      if [[ "${img}" == "${HOST_REG}/"* ]]; then
        "${ENGINE}" push "${img}" || warn "push failed: ${img}"
      fi
    fi
  done < <(export_list)
  # Also push if images were saved under HOST_REG from export
  ok "import complete"
  cmd_status || true
}

cmd_env_snippet() {
  cat <<EOF
# Paste into .env (or rely on compose defaults after seed)

# Host engine pulls (compose image:)
EVERFLOW_FRONTEND_IMAGE=$(host_ref everflow-frontend)
EVERFLOW_BACKEND_IMAGE=$(host_ref everflow-backend)
EVERFLOW_SANDBOX_AGENT_IMAGE=$(host_ref everflow-sandbox-agent)
SEARXNG_IMAGE=$(host_ref upstream-searxng)

# msb / agent guest pull (compose service DNS — not localhost)
SANDBOX_DEFAULT_IMAGE=$(int_ref everflow-sandbox-guest)

# Optional: agent rebuild base
# MICRO_SANDBOX_BASE=$(host_ref upstream-microsandbox)
EOF
}

cmd_write_env_hints() {
  if [[ -f "${ROOT}/.env" ]]; then
    log "Updating .env image refs for local registry"
    # shellcheck disable=SC1091
    if [[ -f "${ROOT}/scripts/lib/everflow-common.sh" ]]; then
      # Minimal inline sets without sourcing full installer
      _set_env() {
        local key="$1" value="$2" f="${ROOT}/.env"
        if grep -q "^${key}=" "${f}" 2>/dev/null; then
          local esc="${value//\\/\\\\}"
          esc="${esc//|/\\|}"
          esc="${esc//&/\\&}"
          sed -i "s|^${key}=.*|${key}=${esc}|" "${f}"
        else
          printf '%s=%s\n' "${key}" "${value}" >>"${f}"
        fi
      }
      _set_env EVERFLOW_FRONTEND_IMAGE "$(host_ref everflow-frontend)"
      _set_env EVERFLOW_BACKEND_IMAGE "$(host_ref everflow-backend)"
      _set_env EVERFLOW_SANDBOX_AGENT_IMAGE "$(host_ref everflow-sandbox-agent)"
      _set_env SEARXNG_IMAGE "$(host_ref upstream-searxng)"
      _set_env SANDBOX_DEFAULT_IMAGE "$(int_ref everflow-sandbox-guest)"
      ok "updated ${ROOT}/.env"
    fi
  else
    log "No .env yet — compose defaults use local registry after seed"
  fi
  echo ""
  cmd_env_snippet
}

usage() {
  cat <<'EOF'
Everflow embedded OCI registry helpers.

Host pushes:  localhost:PORT/everflow/...
msb pulls:    registry:PORT/everflow/...  (compose DNS)

Commands:
  up                 Start registry compose service
  mirror-upstream    Pull microsandbox + searxng → local registry
  build-push         Build Everflow images and push to local registry
  mirror-ghcr        Retag published GHCR images → local (no build)
  seed               mirror-upstream + build-push (or SEED_FROM_GHCR=1)
  status             Catalog + health
  export PATH.tar    Save images for airgap transfer
  import PATH.tar    Load + push into local registry
  env-snippet        Print recommended .env lines

Env: REGISTRY_HOST_PORT CONTAINER_ENGINE EVERFLOW_IMAGE_TAG ONLY SEED_FROM_GHCR
EOF
}

main() {
  local cmd="${1:-}"
  shift || true
  case "${cmd}" in
    up) cmd_up "$@" ;;
    mirror-upstream) cmd_mirror_upstream "$@" ;;
    build-push) cmd_build_push "$@" ;;
    mirror-ghcr) cmd_mirror_ghcr "$@" ;;
    seed) cmd_seed "$@" ;;
    status) cmd_status "$@" ;;
    export) cmd_export "$@" ;;
    import) cmd_import "$@" ;;
    env-snippet | env) cmd_env_snippet "$@" ;;
    -h | --help | help | "") usage ;;
    *) die "unknown command: ${cmd}" ;;
  esac
}

main "$@"
